### ISSUE TITLE
ideally use lxml and not BS4 for html parsing

### ISSUE THREAD

**Issue by mdaniel** [further-reading/scrapy-gui#13]
The selector library underpinning Scrapy [uses `lxml.html.HTMLParser`](https://github.com/scrapy/parsel/blob/v1.5.2/parsel/selector.py#L20), and [not BS4](https://github.com/further-reading/scrapy-gui/blob/master/scrapy_gui/main.py#L40). In the ideal world if one wished to make a GUI tool for testing Scrapy outcomes, then it would make the most sense to use the same HTML parser as Scrapy. It appears one can use [`BeautifulSoup("lxml")`](https://www.crummy.com/software/BeautifulSoup/bs4/doc/#installing-a-parser) to have it use `lxml` under the covers, but it's hard to know what ways BS4 might further try and "help" the parsing

**Comment by further-reading** [comment]
The app doesn't use BS4 for parsing any queries. What you linked is in the source viewer object and it's only used to prettify the text before displaying it in the source tab.
